name: main
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: build external dependencies
        shell: cmd
        working-directory: framework/external
        run: call build_externals_windows.bat
      - name: build game
        shell: cmd
        working-directory: Oxygen/sonic3air/build/_vstudio
        run: msbuild sonic3air.sln /p:Configuration=Release /p:Platform=x64 -verbosity:minimal
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: s3a
          path: .
